//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitPantry.Iota.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitPantry.Iota.Test.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bible 
        ///    translationShortName=&quot;ESV&quot;
        ///    translationLongName=&quot;English Standard Version&quot;
        ///    classification=&quot;Protestant&quot;
        ///    description=&quot;The Holy Bible, English Standard Version. ESV® Text Edition: 2016. Copyright © 2001 by Crossway Bibles&quot;&gt;
        ///  &lt;testament name=&quot;Old&quot;&gt;
        ///    &lt;book number=&quot;1&quot;&gt;
        ///      &lt;chapter number=&quot;1&quot;&gt;
        ///        &lt;verse number=&quot;1&quot;&gt;In the beginning, God created the heavens and the earth.&lt;/verse&gt;
        ///        &lt;verse number=&quot;2&quot;&gt;The earth was without form a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_ESV {
            get {
                return ResourceManager.GetString("Bible_ESV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bible 
        ///    translationShortName=&quot;ESV&quot;
        ///    translationLongName=&quot;English Standard Version&quot;
        ///    classification=&quot;badClass&quot;
        ///    description=&quot;The Holy Bible, English Standard Version. ESV® Text Edition: 2016. Copyright © 2001 by Crossway Bibles&quot;&gt;
        ///  &lt;testament name=&quot;Old&quot;&gt;
        ///    &lt;book number=&quot;1&quot;&gt;
        ///      &lt;chapter number=&quot;1&quot;&gt;
        ///        &lt;verse number=&quot;1&quot;&gt;In the beginning, God created the heavens and the earth.&lt;/verse&gt;
        ///        &lt;verse number=&quot;2&quot;&gt;The earth was without form and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_ESV_badClassification {
            get {
                return ResourceManager.GetString("Bible_ESV_badClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;bible 
        ///    translationShortName=&quot;ESV&quot;
        ///    translationLongName=&quot;English Standard Version&quot;
        ///    classification=&quot;Protestant&quot;
        ///    description=&quot;The Holy Bible, English Standard Version. ESV® Text Edition: 2016. Copyright © 2001 by Crossway Bibles&quot;&gt;
        ///  &lt;testament name=&quot;First&quot;&gt;
        ///    &lt;book number=&quot;1&quot;&gt;
        ///      &lt;chapter number=&quot;1&quot;&gt;
        ///        &lt;verse number=&quot;1&quot;&gt;In the beginning, God created the heavens and the earth.&lt;/verse&gt;
        ///        &lt;verse number=&quot;2&quot;&gt;The earth was without form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_ESV_badTestamentName {
            get {
                return ResourceManager.GetString("Bible_ESV_badTestamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;bible
        ///    translationShortName=&quot;MSG&quot;
        ///    translationLongName=&quot;The Message&quot;
        ///    classification=&quot;Protestant&quot;
        ///    description=&quot;The Message: The Bible in Contemporary Language. Copyright © 2002 by Eugene H. Peterson. All rights reserved. Published by NavPress, a ministry of The Navigators.&quot;&gt;
        ///  &lt;testament name=&quot;Old&quot;&gt;
        ///    &lt;book number=&quot;1&quot;&gt;
        ///      &lt;chapter number=&quot;1&quot;&gt;
        ///        &lt;verse number=&quot;1&quot;&gt;First this: God created the Heavens and Earth--all you see, all you don&apos;t  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bible_MSG {
            get {
                return ResourceManager.GetString("Bible_MSG", resourceCulture);
            }
        }
    }
}
